config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }

  # Assignees Routes
  resources :assignees, only: [:index, :show, :edit, :update] do
    post "send_data_to_assignee", on: :member, as: :send_data_to_assignee
    post "generate_pdf_report", on: :collection
    resources :vacations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/assignee_profile/:id", to: "assignees#assignee_profile", as: "assignee_profile", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "assignees/retrieve_assignees"

  # Projects Routes
  resources :projects do
    resources :quotes, only: [:new, :create, :index, :edit, :update]
    post "generate_pdf_report", on: :collection
    member do
      post "update_project_status", to: "projects#update_project_status"
    end
  end

  get "/project_details/:id", to: "projects#project_details", as: "project_details", constraints: lambda { |request| request.env["warden"].user.admin? }

  # Tasks Routes
  resources :tasks, only: [:index, :show]

  # Admin Routes
  resources :admin, only: [:index]

  post "admin/generate_assignees_report"
  post "admin/db_task_cleaner"
  post "admin/retrieve_tasks"
  post "admin/destroy_all"
  get "/all_vacations", to: "admin#all_vacations", as: "all_vacations", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/flagged_tasks", to: "admin#flagged_tasks", as: "flagged_tasks", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/sidekiq_logs", to: "admin#sidekiq_logs", as: "sidekiq_logs", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "start_slack_message_job/:task_id", to: "admin#start_slack_message_job", as: "start_slack_message_job"
  post "start_jira_issue_comment_job/:task_id", to: "admin#start_jira_issue_comment_job", as: "start_jira_issue_comment_job"

  get "/daily_reports", to: "admin#daily_reports", as: "daily_reports", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "admin/daily_reports", to: "admin#daily_reports", as: "admin_daily_reports"
  post "admin/daily_reports", to: "admin#daily_reports"

  # Home page routes
  root to: "pages#home"
end

app/views/admin/all_vacations.html.erb
<div class="d-flex flex-nowrap gap-1 justify-content-between">
  <div class="list-group pt-4 w-50">
    <h3>Assignees in vacations today:</h3>
    <% @active_vacations.each do |vacation| %>
      <a href=<%= assignee_vacations_path(vacation.assignee) %> class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <div>
            <h5 class="mb-1"><%= vacation.assignee.name %></h5>
            <p class="mb-1"><%= vacation.reason %></p>
            <small class="text-muted">
              Starts: <%= vacation.start_date %><br>
              Ends: <%= vacation.end_date %><br>
            </small>
          </div>
          <small class="text-muted">Duration: 
            <% if vacation.duration %>
              <% if vacation.duration % 1 == 0.5 %>
                <span class="font-weight-bold text-secondary"><%= number_with_precision(vacation.duration, precision: 1) %></span> days
              <% else %>
                <span class="font-weight-bold text-secondary"><%= vacation.duration.to_i %></span> days
              <% end %>
            <% else %>
              <span class="font-weight-bold text-danger">N/A</span>
            <% end %></small>
        </div>
      </a>
    <% end %>
  </div>
  <div class="list-group pt-4 w-50  ">
    <h3>Upcoming Vacations:</h3>
    <% @upcoming_vacations.each do |vacation| %>
      <a href= <%= assignee_vacations_path(vacation.assignee) %> class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <div>
            <h5 class="mb-1"><%= vacation.assignee.name %></h5>
            <p class="mb-1"><%= vacation.reason %></p>
            <small class="text-muted">
              Starts: <%= vacation.start_date %><br>
              Ends: <%= vacation.end_date %><br>
            </small>
          </div>
          <small class="text-muted">Duration: 
            <% if vacation.duration %>
              <% if vacation.duration % 1 == 0.5 %>
                <span class="font-weight-bold text-secondary"><%= number_with_precision(vacation.duration, precision: 1) %></span> days
              <% else %>
                <span class="font-weight-bold text-secondary"><%= vacation.duration.to_i %></span> days
              <% end %>
            <% else %>
              <span class="font-weight-bold text-danger">N/A</span>
            <% end %></small>
        </div>
      </a>
    <% end %>
  </div>
</div>
<div class="list-group py-4">
  <h3>Past Vacations:</h3>
  <% @passed_vacations.each do |vacation| %>
    <a href=<%= assignee_vacations_path(vacation.assignee) %> class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <div class="d-flex flex-column">
          <p class="mb-0">
            <strong><%= vacation.assignee.name %></strong> | <%= vacation.reason %> |
            Starts: <%= vacation.start_date %> | Ends: <%= vacation.end_date %> | 
            Duration: <% if vacation.duration %>
              <% if vacation.duration % 1 == 0.5 %>
                <%= number_with_precision(vacation.duration, precision: 1) %> days
              <% else %>
                <%= vacation.duration.to_i %> days
              <% end %>
            <% else %>
              N/A
            <% end %>
          </p>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/admin/daily_reports.html.erb
<div class="container py-3">
  <h1>Team Daily Reports</h1>
  <%= form_tag(admin_daily_reports_path, method: :get) do %>
    <div class="mb-3 d-flex align-items-center">
      <%= label_tag :selected_date, "Select Date:" %>
      <%= text_field_tag :selected_date, @date_today, id: "flatpickr-date", class: "form-control mr-2 ms-2 mt-2", style: "width: 150px;" %>
      <%= submit_tag "Update", class: "btn btn-sm btn-primary ms-1 mt-2" %>
    </div>
  <% end %>
  <p>Only active team members are shown here<br>
    Total assignees: <%= @assignees.count %> -- Active assignees: <%= @active_assignees.count %></p>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <% @active_assignees.each do |assignee| %>
      <% total_time_spent_today = 0 %>
      <% assignee_worklogs = TaskWorklog.joins(:task)
                              .where(tasks: { assignee_id: assignee.id })
                              .where("DATE(task_worklogs.created) = ?", @date_today) %>
      <% next if assignee_worklogs.empty? %>
      <div class="col">
        <div class="card border-secondary mb-3 card-custom" style="max-width: 19rem; display: flex; flex-direction: column; justify-content: space-between;">
          <div class="card-header text-center"><%= assignee.name %></div>
          <div class="card-body text-secondary">
            <h5 class="card-title text-center">Report: <%= @date_today %></h5>
            <ul class="list-group list-group-flush">
              <% assignee_worklogs.each do |worklog| %>
                <% worklog_duration = worklog.duration.to_i %>
                <li class="list-group-item">
                  <%= "#{worklog.task.jira_id}: #{my_helper_format_duration(worklog_duration)}" %> <br>
                </li>
                <% total_time_spent_today += worklog_duration %>
              <% end %>
            </ul>
          </div>
          <div class="card-footer text-end">
            <h4>Total: <%= my_helper_format_duration(total_time_spent_today) %></h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/flagged_tasks.html.erb
<div class="container py-2">
  <div class="row">
    <div class="text-small"><%= @tasks.count %> tasks</div>
    <% @tasks.order(updated_at: :desc).each do |task| %>
      <div class="col-md-2 mb-1 px-1">
        <div class="card" style="height: 100%;">
          <div class="card-header d-flex align-items-center justify-content-between py-0">
            <h6 class="mb-0" style="font-size: 14px;">
              <%= link_to task.jira_id, "https://agenceinspire.atlassian.net/browse/#{task.jira_id}", target: "_blank" %>
            </h6>
            <div>
              <a href="<%= start_jira_issue_comment_job_path(task) %>" class="btn btn-link p-0" data-method="post">
                <i class="bi bi-chat-dots" style="color: black;"></i>
              </a>
              <a href="<%= start_slack_message_job_path(task) %>" class="btn btn-link p-0" data-method="post">
                <i class="bi bi-slack" style="color: black;"></i>
              </a>
            </div>
          </div>
          <div class="card-body py-1" style="font-size: 12px;">
            <p class="mb-0"><strong>Assignee: </strong><%= task.assignee.name %></p>
            <p class="mb-0"><strong>Lead: </strong><%= task.reporter %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/index.html.erb
<div class="container py-4">
  <div class="d-flex flex-wrap justify-content-between align-items-start">
    <div class="btn-group" role="group" aria-label="button-group-pages">
      <div class="btn-group-vertical">
        <%= button_to('Vacations', all_vacations_path, method: :get, class: 'btn btn-outline-success mx-1 my-1') %>
        <%= button_to('Sidekiq Logs', sidekiq_logs_path, method: :get, class: 'btn btn-outline-success mx-1 my-1') %>
        <%= button_to('Flagged Tasks - Slack Test', flagged_tasks_path, method: :get, class: 'btn btn-outline-dark mx-1 my-1') %>
        <%= button_to('Daily reports', daily_reports_path, method: :get, class: 'btn btn-outline-dark mx-1 my-1') %>
        <%= button_to('Check tasks against source', { action: 'db_task_cleaner' }, method: :post, class: 'btn btn-info mx-1 my-1') %>
        <%= button_to('Import tasks from JIRA', { action: 'retrieve_tasks' }, method: :post, class: 'btn btn-warning mx-1 my-1') %>
        <%= button_to('Delete all tasks', { action: 'destroy_all' }, method: :post, data: { confirm: 'Are you sure you want to delete all tasks?' }, class: 'btn btn-danger mx-1 my-1') %>
        <br>
        <%= button_to('Generate Assignees Report for 2023', { action: 'generate_assignees_report' }, method: :post, class: 'btn btn-success mx-1 my-1') %>
      </div>
    </div>
  </div>
</div>

app/views/admin/sidekiq_logs.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Created At</th>
      <th>Execution Time</th>
    </tr>
  </thead>
  <tbody>
    <% JobsLog.order(created_at: :desc).limit(20).each do |joblog| %>      
      <tr>
        <td><%= joblog.title %></td>
        <td><%= joblog.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= my_helper_format_duration(joblog.execution_time) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/sidekiq_scheduler_logs.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Created At</th>
      <th>Execution Time</th>
    </tr>
  </thead>
  <tbody>
    <% JobsLog.all.order(created_at: :desc).each do |joblog| %>
      <tr>
        <td><%= joblog.title %></td>
        <td><%= joblog.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= my_helper_format_duration(joblog.execution_time) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/tests.html.erb
<div class="container py-2">
  <div class="row">
    <div class="text-small"><%= @tasks.count %> tasks</div>
    <% @tasks.order(updated_at: :desc).each do |task| %>
      <div class="col-md-2 mb-1 px-1">
        <div class="card" style="height: 100%;">
          <div class="card-header d-flex align-items-center justify-content-between py-0">
            <h6 class="mb-0" style="font-size: 14px;">
              <%= link_to task.jira_id, "https://agenceinspire.atlassian.net/browse/#{task.jira_id}", target: "_blank" %>
            </h6>
            <div>
              <a href="<%= start_jira_issue_comment_job_path(task) %>" class="btn btn-link p-0" data-method="post">
                <i class="bi bi-chat-dots" style="color: black;"></i>
              </a>
              <a href="<%= start_slack_message_job_path(task) %>" class="btn btn-link p-0" data-method="post">
                <i class="bi bi-slack" style="color: black;"></i>
              </a>
            </div>
          </div>
          <div class="card-body py-1" style="font-size: 12px;">
            <p class="mb-0"><strong>Assignee: </strong><%= task.assignee.name %></p>
            <p class="mb-0"><strong>Lead: </strong><%= task.reporter %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>