config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }

  # Assignees Routes
  resources :assignees, only: [:index, :show, :edit, :update] do
    post "send_data_to_assignee", on: :member, as: :send_data_to_assignee
    post "generate_pdf_report", on: :collection
    resources :vacations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/assignee_profile/:id", to: "assignees#assignee_profile", as: "assignee_profile", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "assignees/retrieve_assignees"

  # Projects Routes
  resources :projects do
    resources :quotes, only: [:new, :create, :index, :edit, :update]
    post "generate_pdf_report", on: :collection
    member do
      post "update_project_status", to: "projects#update_project_status"
    end
  end

  get "/project_details/:id", to: "projects#project_details", as: "project_details", constraints: lambda { |request| request.env["warden"].user.admin? }

  # Tasks Routes
  resources :tasks, only: [:index, :show]

  # Admin Routes
  resources :admin, only: [:index]

  post "admin/generate_assignees_report"
  post "admin/db_task_cleaner"
  post "admin/retrieve_tasks"
  post "admin/destroy_all"
  get "/all_vacations", to: "admin#all_vacations", as: "all_vacations", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/flagged_tasks", to: "admin#flagged_tasks", as: "flagged_tasks", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/sidekiq_logs", to: "admin#sidekiq_logs", as: "sidekiq_logs", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "start_slack_message_job/:task_id", to: "admin#start_slack_message_job", as: "start_slack_message_job"
  post "start_jira_issue_comment_job/:task_id", to: "admin#start_jira_issue_comment_job", as: "start_jira_issue_comment_job"

  get "/daily_reports", to: "admin#daily_reports", as: "daily_reports", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "admin/daily_reports", to: "admin#daily_reports", as: "admin_daily_reports"
  post "admin/daily_reports", to: "admin#daily_reports"

  # Home page routes
  root to: "pages#home"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  
<div class="footer">
  <div class="footer-links">
    <a href="https://inspiregroup.io"><i class="bi bi-globe"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This app is made by & for the Inspire Group <i class="bi bi-rocket"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <div class="container-fluid">
    <div class="navbar-brand-container">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Dev Panel", admin_index_path , class: "nav-link  text-danger" %>
            </li>
          <% end %>
            <li class="nav-item">
              <%= link_to "All the Tasks", tasks_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Projects", projects_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Assignees", assignees_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://img.freepik.com/premium-vector/color-diamong-icon-magic-gem-jewel-sign_543062-2891.jpg?w=2000", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <p class="small-text nav-link">
                  <%= current_user.name %>
                  <%= current_user.email %>
                </p>
                <%= form_tag destroy_user_session_path, method: :delete, class: "nav-link" do %>
                  <%= submit_tag "Sign out" %>
                <% end %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>
<%= render "shared/flashes" %>