config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }

  # Assignees Routes
  resources :assignees, only: [:index, :show, :edit, :update] do
    post "send_data_to_assignee", on: :member, as: :send_data_to_assignee
    post "generate_pdf_report", on: :collection
    resources :vacations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/assignee_profile/:id", to: "assignees#assignee_profile", as: "assignee_profile", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "assignees/retrieve_assignees"

  # Projects Routes
  resources :projects do
    resources :quotes, only: [:new, :create, :index, :edit, :update]
    post "generate_pdf_report", on: :collection
    member do
      post "update_project_status", to: "projects#update_project_status"
    end
  end

  get "/project_details/:id", to: "projects#project_details", as: "project_details", constraints: lambda { |request| request.env["warden"].user.admin? }

  # Tasks Routes
  resources :tasks, only: [:index, :show]

  # Admin Routes
  resources :admin, only: [:index]

  post "admin/generate_assignees_report"
  post "admin/db_task_cleaner"
  post "admin/retrieve_tasks"
  post "admin/destroy_all"
  get "/all_vacations", to: "admin#all_vacations", as: "all_vacations", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/flagged_tasks", to: "admin#flagged_tasks", as: "flagged_tasks", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/sidekiq_logs", to: "admin#sidekiq_logs", as: "sidekiq_logs", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "start_slack_message_job/:task_id", to: "admin#start_slack_message_job", as: "start_slack_message_job"
  post "start_jira_issue_comment_job/:task_id", to: "admin#start_jira_issue_comment_job", as: "start_jira_issue_comment_job"

  get "/daily_reports", to: "admin#daily_reports", as: "daily_reports", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "admin/daily_reports", to: "admin#daily_reports", as: "admin_daily_reports"
  post "admin/daily_reports", to: "admin#daily_reports"

  # Home page routes
  root to: "pages#home"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_many :quotes, dependent: :destroy
  paginates_per 20

end

app/views/pages/_slider.html.erb
<div class="py-3">
  <div id="projectSlider" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @projects_with_active_tickets.each_with_index do |project, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
          <h2><%= project.name %></h2>
          <%= render partial: 'slider_card', locals: { project: project } %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#projectSlider" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#projectSlider" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
</div>

app/views/pages/_slider_card.html.erb
<div class="row py-3">
  <% project.task_ids.each do |task| %>
    <% task = Task.find(task) %>
    <div class="col-md-6 col-xl-3 mb-3">
      <div class="card card-task">
        <div class="card-body row">
          <div class="col-4">
            <%= link_to root_path, class: "img-fluid rounded-circle" do %>
              <%= image_tag "neutral_avatar.png", width: 75, height: 75 %>
            <% end %>
          </div>
          <div class="col-8 card-title align-self-center mb-0">
            <h5 class="text-center"><%= link_to truncate(task.assignee.name, length: 20), assignee_path(task.assignee) %></h5>
            <p class="text-center m-0">
              <%= link_to task.jira_id, task_path(task) %>
              &nbsp;<a href="https://agenceinspire.atlassian.net/browse/<%= task.jira_id %>" target="_blank">
                <span><i class="bi bi-box-arrow-up-right"></i></span>
              </a>
            </p>
          </div>
        </div>
        <ul class="list-group list-group-flush small">
          <li class="list-group-item"><i class="fa fa-envelope float-right"></i><strong>Original Estimate: </strong>
            <% if my_helper_format_duration(task.time_forecast) == "No data" %>
              <span class="flashing-text">No data</span>
            <% else %>
              <%= my_helper_format_duration(task.time_forecast) %>
            <% end %>
          </li>
          <% if task.time_forecast.nil? || task.time_spent.nil? %>
            <li class="list-group-item"><strong>Time remaining:</strong> <span class="flashing-text">No data</span></li>
          <% else %>
            <% remaining_time = task.time_forecast - task.time_spent %>
            <li class="list-group-item"><strong>Time remaining:</strong> <%= my_helper_format_duration(remaining_time) %></li>
          <% end %>
        </ul>
        <div class="card-body text-center">
          <% @other_tasks = Task.where(assignee_id: task.assignee).where(status: ["To Do", "A faire", "A faire ce jour"]) %>
          <% if @other_tasks.blank? %>
            <p class="small m-0">Nothing else planned for <strong><%= task.assignee.name %></strong> <i class="bi bi-emoji-smile text-success"></i></p>
          <% else %>
            <p class="small m-0"><strong><%= task.assignee.name %></strong> has <span class="badge bg-secondary display-4"><%= @other_tasks.count %></span> other tasks on their plate</p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_tasks_accordion.html.erb
<div class="row">
  <% project.task_ids.each do |task| %>
    <% task = Task.find(task) %>
    <div class="col-md-4">
      <div class="card active-task-card m-1">
        <div class="card-body-active-card">
          <div class="d-flex justify-content-between align-items-center">
            <div class="fw-bold text-muted small-text">
              <%= task.status %>: <%= link_to task.jira_id, task_path(task) %>
              &nbsp;<a href="https://agenceinspire.atlassian.net/browse/<%= task.jira_id %>" target="_blank">
                <span><i class="bi bi-box-arrow-up-right"></i></span>
              </a>
            </div>
            <%= link_to truncate(task.assignee.name, length: 20), assignee_path(task.assignee) %>
            <span class="text-muted small-text"> <%= task.status %></span>
          </div>
          <% if task.time_forecast.nil? || task.time_spent.nil? %>
            <div class="progress mt-2">
              <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 100%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1"> No data</div>
            </div>
          <% else %>
            <% remaining_time = task.time_forecast - task.time_spent %>
            <% status_class = case remaining_time <=> 0
                            when -1 then 'text-danger'
                            when 0 then 'text-warning'
                            else 'text-success'
                            end %>
            <div class="progress mt-2">
              <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= (task.time_spent / task.time_forecast) * 100 %>%;" aria-valuenow=<% task.time_spent %> aria-valuemin="0" aria-valuemax=<% task.time_forecast %>>
                <span class="<%= status_class %> remaining-time" style="color:white !important;"><%= "#{my_helper_format_duration(remaining_time)} remaining..." %></span>
              </div>
            </div>
          <% end %>
          <div>
            <p class="text-center font-weight-light small-text" >Original Estimate: <%= my_helper_format_duration(task.time_forecast) %> </p>
          </div>
          <p class="card-text text-center font-weight-light small-text pt-0 pb-0 mt-0 mb-0"> <%= truncate(task.summary, length: 60) %> </p>
        </div>
        <div class="d-flex align-items-center justify-content-between mx-2">
          <div class="small-text">
            <% if task.assignee.on_vacation? %>
              <span class="badge bg-warning">On Vacation</span>
            <% end %>
          </div>
          <div class="small-text text-muted">
            <% if task.due_date.present? %>
              <div>Start date: <%= task.status_change_date.strftime("%e %B %Y")  %></div>
              <div>Due Date: <%= task.due_date.strftime("%e %B %Y") %></div>
            <% else %>
              No Data
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
  <!-- Dashboard Metrics -->
<div class="row justify-content-center mt-2">
  <div class="col-md-2 text-center">
    <p class="text-muted">"In Progress" Tasks</p>
    <h3><%= @in_progress_tasks_count %></h3>
  </div>
  <div class="col-md-2 text-center">
    <p class="text-muted">Tasks On Hold</p>
    <h3><%= @on_hold_tasks_count %></h3>
  </div>
  <div class="col-md-2 text-center">
    <p class="text-muted">Number of tickets</p>
    <div class="position-relative">
      <%= link_to tasks_path, class: "d-inline-block position-relative" do %>
        <h3 class="d-inline"><%= @total_number_of_tasks %></h3>
        <% if !@total_number_of_tasks_today.nil? %>
          <span class="position-absolute top-0 start-100 ms-3 translate-middle badge rounded-pill bg-success text-light" style="transform: translate(50%, -50%); font-size: 1em; width: 2em;">
            +<%= @total_number_of_tasks_today %>
          </span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="py-3"><%= render partial: 'slider'%></div>
<div class="fixed-bottom bg-light p-2 text-center">
  <% if !@last_jira_update.nil? %>
    <span class="small-text text-muted">
      Last update: <strong><%= distance_of_time_in_words(@last_jira_update.created_at, Time.current, include_seconds: true) %> ago</strong>
      it lasted: <strong><%= number_with_precision(@last_jira_update.execution_time, precision: 1) %> s</strong>
    </span>
  <% end %>
</div>