config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }

  # Assignees Routes
  resources :assignees, only: [:index, :show, :edit, :update] do
    post "send_data_to_assignee", on: :member, as: :send_data_to_assignee
    post "generate_pdf_report", on: :collection
    resources :vacations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get "/assignee_profile/:id", to: "assignees#assignee_profile", as: "assignee_profile", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "assignees/retrieve_assignees"

  # Projects Routes
  resources :projects do
    resources :quotes, only: [:new, :create, :index, :edit, :update]
    post "generate_pdf_report", on: :collection
    member do
      post "update_project_status", to: "projects#update_project_status"
    end
  end

  get "/project_details/:id", to: "projects#project_details", as: "project_details", constraints: lambda { |request| request.env["warden"].user.admin? }

  # Tasks Routes
  resources :tasks, only: [:index, :show]

  # Admin Routes
  resources :admin, only: [:index]

  post "admin/generate_assignees_report"
  post "admin/db_task_cleaner"
  post "admin/retrieve_tasks"
  post "admin/destroy_all"
  get "/all_vacations", to: "admin#all_vacations", as: "all_vacations", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/flagged_tasks", to: "admin#flagged_tasks", as: "flagged_tasks", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "/sidekiq_logs", to: "admin#sidekiq_logs", as: "sidekiq_logs", constraints: lambda { |request| request.env["warden"].user.admin? }
  post "start_slack_message_job/:task_id", to: "admin#start_slack_message_job", as: "start_slack_message_job"
  post "start_jira_issue_comment_job/:task_id", to: "admin#start_jira_issue_comment_job", as: "start_jira_issue_comment_job"

  get "/daily_reports", to: "admin#daily_reports", as: "daily_reports", constraints: lambda { |request| request.env["warden"].user.admin? }
  get "admin/daily_reports", to: "admin#daily_reports", as: "admin_daily_reports"
  post "admin/daily_reports", to: "admin#daily_reports"

  # Home page routes
  root to: "pages#home"
end

app/models/assignee.rb
class Assignee < ApplicationRecord
  has_many :tasks
  has_many :vacations

  after_initialize :set_assignee_vacation_days

  validates :name, uniqueness: true
  validates :email, uniqueness: true

  paginates_per 50

  validate :vacation_days_non_negative

  private

  def set_assignee_vacation_days
    if self.vacation_days_available.nil? || vacation_days_available.negative?
      self.vacation_days_available = 0
    end
  end

  def vacation_days_non_negative
    if vacation_days_available.negative? || vacation_days_available.nil?
      errors.add(:vacation_days_available, "You can't have vacation debts!")
    end
  end
end

app/controllers/assignees_controller.rb
class AssigneesController < ApplicationController
  def index
    breadcrumbs.add "Assignees", assignees_path
    @assignees = Assignee
      .select("assignees.*, MAX(tasks.last_jira_update)")
      .joins("LEFT JOIN tasks ON tasks.assignee_id = assignees.id")
      .group("assignees.id")
      .order("MAX(tasks.last_jira_update) DESC")
      .page(params[:page])

    @assignees_count = Assignee.count
  end

  def retrieve_assignees
    url = "https://agenceinspire.atlassian.net/rest/api/3/user/search?query=+&maxResults=1000"
    response = call_jira_api(url)
    return unless response.code == "200"

    json_assignee = JSON.parse(response.body)
    json_assignee.each do |assignee|
      assignee_name = assignee["displayName"]
      assignee_email = assignee["emailAddress"]
      find_or_create_assignee(assignee_name, assignee_email)
    end

    redirect_to assignees_path
  end

  def send_data_to_assignee
    assignee = Assignee.find(params[:id])
    ReportMailer.send_data_to_user(assignee).deliver_now
    redirect_to assignee_path, notice: "Data sent to assignee"
  end

  def edit
    @assignee = Assignee.find(params[:id])
    breadcrumbs.add "Admin view: #{@assignee.name}", assignee_profile_path(@assignee)
  end

  def update
    @assignee = Assignee.find(params[:id])
    if @assignee.update(assignee_params)
      redirect_to request.referrer || assignee_profile_path(@assignee), notice: "Assignee was updated."
    else
      render :edit
    end
  end

  def show
    @assignee = Assignee.find(params[:id])
    breadcrumbs.add "Prod view: #{@assignee.name}", assignees_path(@assignee)
    @assignee_tasks = Task.where(assignee: @assignee).order(last_jira_update: :desc)
    generate_cr(Date.today)
    assignee_unique_projects_list
    @tasks_by_time_status = tasks_by_time_status
    @assignee_tasks_paginated = Task.where(assignee: @assignee).order(last_jira_update: :desc).page(params[:page])
    calculate_time_statistics
    calculate_task_ratio_sum
    @assignee_ratio = calculate_assignee_ratio
  end

  def assignee_profile
    @assignee = Assignee.find(params[:id])
    breadcrumbs.add "Admin view: #{@assignee.name}", assignee_profile_path(@assignee)
    @assignees_projects = Project.joins(:tasks).where(tasks: { assignee_id: @assignee.id })
      .select("projects.*, SUM(tasks.time_spent) AS total_time_spent")
      .group("projects.id")
  end

  def generate_pdf_report
    pdf = Prawn::Document.new
    assignee = Assignee.find(params[:id])

    pdf.font("Helvetica", size: 18)
    pdf.text "<b>#{assignee.name}</b> - <font size='14'> Brut: #{assignee.salary} TND - Hourly Cost: #{assignee.hourly_rate} TND </font>", :inline_format => true

    pdf.font("Helvetica", size: 12, style: :bold)
    # Calculate total tasks, time estimated, and time spent in 2023
    total_tasks = assignee.tasks.count
    total_tasks_2023 = assignee.tasks.where("extract(year from created_at) = ?", 2023).count
    total_time_estimated = assignee.tasks.where("extract(year from created_at) = ?", 2023).sum(:time_forecast)
    total_time_spent = assignee.tasks.where("extract(year from created_at) = ?", 2023).sum(:time_spent)

    pdf.text "Total tasks: #{total_tasks}"
    pdf.text "Total tasks in 2023: #{total_tasks_2023}"
    pdf.text "Total time estimated on JIRA in 2023: #{format_duration(total_time_estimated)}"
    pdf.text "Total time logged on JIRA in 2023: #{format_duration(total_time_spent)} - <font size='12'> #{(assignee.hourly_rate.to_f * (total_time_spent.to_f / 3600.0).round(2)).round(2)} TND </font>", :inline_format => true

    pdf.font("Helvetica", size: 10, style: :normal)
    pdf.text "\n"

    tasks_per_project = list_of_assignee_tasks_per_project(assignee)
    tasks_per_project.each do |project|
      project_cost_2023 = project_cost_2023(project.name)
      time_spent = stats_of_unique_project_by_assignee(project, assignee, 2023)
      assignee_project_cost = (assignee.hourly_rate.to_f * (time_spent.to_f / 3600.0).round(2)).round(2)

      pdf.text "\n#{project.name}\n Cost in 2023: <b>#{project_cost_2023} TND</b>", :inline_format => true
      pdf.text "#{assignee.name} logged <b>#{format_duration(time_spent)}</b> on JIRA", :inline_format => true
      pdf.text "Individual cost <font size='10'> <b>#{assignee_project_cost} TND </b></font> - That's #{(assignee_project_cost.to_f / project_cost_2023.to_f * 100).round(2)} % from total", :inline_format => true
    end

    pdf.move_down(10) # Add space between sections

    send_data pdf.render, filename: "Report #{assignee.name}.pdf", type: "application/pdf", disposition: "attachment"
  end

  private

  def project_cost_2023(project_name)
    project = Project.where(name: project_name).first
    total_time_spent_2023 = project.tasks.where("extract(year from created_at) = ?", 2023).sum(:time_spent)
    (total_time_spent_2023.to_f / 3600.0.round(2) * 25).round(2)
  end

  def list_of_assignee_tasks_per_project(assignee)
    assignee.tasks.joins(:project).select("distinct projects.*")
  end

  def stats_of_unique_project_by_assignee(project, assignee, year)
    tasks = assignee.tasks.where(project: project).where("extract(year from created_at) = ?", year)
    tasks.sum(:time_spent)
  end

  def assignee_params
    params.require(:assignee).permit(:name, :email, :admin, :salary, :hourly_rate, :vacation_days_available, :on_vacation)
  end

  def find_or_create_assignee(assignee_name, assignee_email, admin: false)
    assignee_name = format_name(assignee_name)
    assignee_email = assignee_email.present? ? assignee_email : format_email(assignee_name)
    Assignee.create(email: assignee_email) do |user|
      user.name = assignee_name
      user.admin = admin
    end
  end

  def generate_cr(day)
    @assignee_todays_tasks = Task.where(assignee: @assignee)
      .where("DATE(last_jira_update) = ? OR DATE(created_at) = ?", day, day)
      .order(last_jira_update: :desc)

    @assignee_yesterday_tasks = Task.where(assignee: @assignee)
      .where("DATE(last_jira_update) = ? OR DATE(created_at) = ?", day - 1, day - 1)
      .order(last_jira_update: :desc)
  end

  def assignee_unique_projects_list
    # Load the assignee by ID
    @assignee = Assignee.find(params[:id])

    # Load all the unique projects for the assignee's tasks
    @project_task_counts = @assignee.tasks.group(:project_id).count
    @projects_jira_ids = []
    @project_task_counts.each do |project_id, task_count|
      project = Project.find(project_id)
      @projects_jira_ids << { project_id: project_id, jira_id: project.jira_id }
    end

    # Calculate task percentages for each project
    @project_task_percentages = {}
    total_tasks = @assignee.tasks.count
    @project_task_counts.each do |project_id, task_count|
      project = Project.find(project_id)
      @project_task_percentages[project.jira_id] = (task_count.to_f / total_tasks * 100).round(2)
    end

    # Sort the projects by the number of tasks in descending order
    @projects_jira_ids.sort_by! { |project| -@project_task_counts[project[:project_id]] }
  end

  def tasks_by_time_status
    assignee = Assignee.find(params[:id])
    total_tasks = assignee.tasks.count
    in_time_tasks = assignee.tasks.where("time_spent = time_forecast").count
    early_tasks = assignee.tasks.where("time_spent < time_forecast").count
    delayed_tasks = assignee.tasks.where("time_spent > time_forecast").count
    no_data_tasks = assignee.tasks.where("time_forecast IS NULL OR time_spent IS NULL").count

    in_time_percentage = (in_time_tasks.to_f / total_tasks.to_f * 100).round(2)
    early_percentage = (early_tasks.to_f / total_tasks.to_f * 100).round(2)
    delayed_percentage = (delayed_tasks.to_f / total_tasks.to_f * 100).round(2)
    no_data_percentage = (no_data_tasks.to_f / total_tasks.to_f * 100).round(2)

    { in_time: { count: in_time_tasks, percentage: in_time_percentage },
      early: { count: early_tasks, percentage: early_percentage },
      delayed: { count: delayed_tasks, percentage: delayed_percentage },
      no_data: { count: no_data_tasks, percentage: no_data_percentage } }
  end

  def calculate_time_statistics
    @total_time_estimation = @assignee_tasks.sum(:time_forecast) || 0
    @total_time_spent = @assignee_tasks.sum(:time_spent) || 0
    @time_difference = @total_time_estimation - @total_time_spent
  end

  def calculate_task_ratio_sum
    @task_ratio_sum = @assignee_tasks.sum { |task| calculate_task_ratio(task) }
  end

  def calculate_assignee_ratio
    (@task_ratio_sum.fdiv(@assignee_tasks.count || 0) * 100).round(2)
  end

  def calculate_task_ratio(task)
    if task.time_forecast && task.time_spent
      task_time_gap = task.time_forecast - task.time_spent
      accepted_gap_ratio = task_time_gap / task.time_forecast
      if accepted_gap_ratio < 0.17
        return 1
      end
    end
    return 0
  end
end

app/views/assignees/_form_vacation_days.html.erb
<div>
  <%= turbo_frame_tag "form_vacation_days" do %>
    <%= simple_form_for(@assignee) do |f| %>
      <%= f.input :vacation_days_available, placeholder: "Insert how many days you want to add."  %>
      <%= f.button :submit, class: "btn btn-secondary", value: "Update" %>
    <% end %>
  <% end %>
</div>

app/views/assignees/_hover_cr_today.html.erb
<div class="hover-content">
  <p>Tasks done today: <%= Date.today %></p>
  <% @assignee_todays_tasks.each do |task| %>
    <% task.task_worklogs.each do |worklog| %>
      <ul>
        <li><%= Task.find_by(id: worklog.task_id).jira_id %>
          <%= my_helper_format_duration(worklog.duration.to_i) %>
          <%= worklog.status %>
        </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/assignees/_hover_cr_yesterday.html.erb
<div class="hover-content">
  <p>Tasks done today: <%= Date.today %></p>
  <% @assignee_yesterday_tasks.each do |task| %>
    <% task.task_worklogs.each do |worklog| %>
      <ul>
        <li><%= Task.find_by(id: worklog.task_id).jira_id %>
          <%= my_helper_format_duration(worklog.duration.to_i) %>
          <%= worklog.status %>
        </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/assignees/assignee_profile.html.erb
<div class="container pt-4" style="max-width: 80%;">
  <div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
      <span><%= @assignee.name %></span>
      <div>
        <%= link_to "Update Information", edit_assignee_path(@assignee), class: "btn btn-dark btn-sm mb-0 text-light ml-auto" %>
        <%= link_to "Vacations", assignee_vacations_path(@assignee), class: "btn btn-success btn-sm mb-0 text-dark ml-auto" -%>
      </div>
    </div>
    <div class="card-body">
      <h5 class="mb-0">
        <%= @assignee.email %>
        <div class="d-flex justify-content-end">
          <%= link_to generate_pdf_report_assignees_path(id: @assignee.id), method: :post, class: 'btn p-0' do %>
            Generate assignee report <i class="bi bi-database-fill-gear" style="color: black;"></i>
          <% end %>
        </div>
      </h5>
      <p class="card-text">
        <div>
          Vacation days available:
          <span class="badge bg-primary text-light">
            <%= number_with_precision(@assignee.vacation_days_available, precision: 1) %> days
          </span></br>
        Salary:
        <span class="badge bg-primary text-light">
          <%= number_with_precision(@assignee.salary, precision: 1) %> TND
        </span></br>
      Hourly rate: 
      <span class="badge bg-primary text-light">
        <%= number_with_precision(@assignee.hourly_rate, precision: 1) %> TND         
      </span>
    </div>
  </p>
</div>
<div class="card-body">
  <table class="table">
    <thead>
      <tr>
        <th>Project</th>
        <th>Total time worked</th>
        <th>Total cost</th>
      </tr>
    </thead>
    <tbody>
      <% @assignees_projects.each do |project| %>
        <tr>
          <td><%= link_to project.jira_id, project %></td>
          <td><%=  my_helper_format_duration(project.total_time_spent) %></td>
          <td>
            <% if @assignee.hourly_rate.present? && @assignee.hourly_rate.to_f != 0 %>
              <%= number_with_precision((project.total_time_spent.to_f / 3600) * @assignee.hourly_rate.to_f, precision: 1) %> TND
            <% else %>
              Check if the assignee hourly rate is set!
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/assignees/edit.html.erb
<div class="container py-4" style="max-width: 50%;">
  <div>
    <%= simple_form_for @assignee do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :admin %>
      <%= f.input :salary %>
      <%= f.input :hourly_rate %>
      <%= f.button :submit, class:"btn btn-dark text-light mb-5" %>
    <% end %>
  </div>
</div>

app/views/assignees/index.html.erb
<div class="container py-4">
  <div align="right" style="font-size: 80%"><%= page_entries_info @assignees, entry_name: 'assignee' %></div>
  <span class="d-flex flex-row-reverse"><%= link_to_next_page @assignees, 'Next' %>&nbsp;&nbsp;<%= link_to_previous_page @assignees, 'Previous' %></span>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th># Tickets</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @assignees.each do |assignee| %>
        <% if assignee.active? %>
          <tr>
            <td><%= assignee.id %></td>
            <td><%= assignee.name %></td>
            <td><%= assignee.email %></td>
            <td><%= assignee.tasks.count %></td>
            <td class="text-end">
              <% if current_user.admin? %>
                <%= link_to generate_pdf_report_assignees_path(id: assignee.id), method: :post, class: 'btn p-0' do %>
                  Generate assignee report <i class="bi bi-database-fill-gear" style="color: black;"></i>
                <% end %>
              <% end %>
              <%= link_to "Prod View", { action: "show", id: assignee.id }, class: "btn btn-secondary btn-sm" %>
              <% if current_user.admin? %>
                <%= link_to "Admin View", { action: "assignee_profile", id: assignee.id }, class: "btn btn-warning btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/assignees/show.html.erb
<div class="container py-4">
  <!-- Statistics -->
  <div class="row justify-content-between mb-4">
    <div class="col-12 col-md-6">
      <div class="d-flex align-items-auto">
        <h1 class="fw-bold mb-3"><%= @assignee.name %></h1>
        <div class="ms-2 small-text pt-2">
          <% if current_user.admin? %>
            <%= link_to "Admin view", assignee_profile_path(@assignee) , class: "btn btn-dark btn-sm mb-0" %>
          <% end %>
          <% if @assignee.on_vacation? %>
            <span class="badge bg-warning ps-1 pt-1">On Vacation</span>
          <% end %>
        </div>
      </div>
      <div>
        <!-- Hover CR -->
        <%= render partial: 'hover_cr_today' %>
        <%= render partial: 'hover_cr_yesterday' %>
        <span class="hover-text"><%= Date.today.strftime("%e %B %Y") %></span>
      </br>
      <span class="hover-text"><%= (Date.today - 1).strftime("%e %B %Y") %></span>
      <% if current_user.admin? %>
        <%= button_to 'DEV: Mailer', send_data_to_assignee_assignee_path, method: :post, class: "btn btn-danger btn-sm mb-0 text-light" %></br>
    <% end %>
  </div>
</div>
<!-- Team / Filtres -->
<div class="col-12 col-md-6">
  <div class="d-flex align-items-center">
    <h1 class="mb-2 me-3">Projects</h1>
    <span class="badge bg-dark fs-6"><%= @assignee_tasks.count %> tickets</span>
  </div>
  <div class="row">
    <% @projects_jira_ids.each do |project| %>
      <div class="col-6">
        <p class="card-text mb-1">
          <%= link_to project[:jira_id], project_path(project[:project_id]) %>
          <span class="badge bg-info text-dark"> <%= @project_task_counts[project[:project_id]] %></span>
          <span class="badge bg-primary"> <%= "#{(@project_task_percentages[project[:jira_id]])} %" %></span>
        </p>
      </div>
    <% end %>
  </div>
</div>
<!-- Stats -->
<div class="col-12 col-md-12 pt-3">
  <h2 class="fw-bold mb-3">Stats</h2>
  <div class="bg-stats border-0">
    <div class="card-body row">
      <div class="col-4">
        <div class="mb-1">
          <span class="badge bg-light text-dark">Total Time Estimated</span>
          <span class="badge bg-secondary"><%= my_helper_format_duration(@total_time_estimation) %></span>
        </div>
        <div class="mb-1">
          <span class="badge bg-light text-dark">Total Time Spent</span>
          <span class="badge bg-secondary"><%= my_helper_format_duration(@total_time_spent) %></span>
        </div>
        <div class="mb-1">
          <span class="badge bg-light text-dark">Difference</span>
          <% color = @time_difference.positive? ? "success" : (@time_difference < 0 ? "danger" : "secondary") %>
          <span class="badge bg-<%= color %>"><%= my_helper_format_duration(@time_difference) %></span>
        </div>
      </div>
      <div class="col-4">
        <div class="mb-1">
          <span class="badge bg-light text-dark">In Time</span>
          <span class="badge bg-success"><%= @tasks_by_time_status[:in_time][:count] %></span>
          <span class="badge bg-success"><%= @tasks_by_time_status[:in_time][:percentage] %>%</span>
        </div>
        <div class="mb-1">
          <span class="badge bg-light text-dark">Early</span>
          <span class="badge bg-warning"><%= @tasks_by_time_status[:early][:count] %></span>
          <span class="badge bg-warning"><%= @tasks_by_time_status[:early][:percentage] %>%</span>
        </div>
        <div class="mb-1">
          <span class="badge bg-light text-dark">Delayed</span>
          <span class="badge bg-danger"><%= @tasks_by_time_status[:delayed][:count] %></span>
          <span class="badge bg-danger"><%= @tasks_by_time_status[:delayed][:percentage] %>%</span>
        </div>
        <div class="mb-1">
          <span class="badge bg-light text-dark">No data</span>
          <span class="badge bg-dark"><%= @tasks_by_time_status[:no_data][:count] %></span>
          <span class="badge bg-dark"><%= @tasks_by_time_status[:no_data][:percentage] %>%</span>
        </div>
      </div>
      <div class="col-4">
        <div class="mb-1">
          <span class="badge bg-light text-dark">Assignee Total Performance Ratio</span>
          <span class="badge bg-success text-dark"><%= @assignee_ratio %>%</span>
        </div>
        <div class="mb-1">
        </div>
        <div class="mb-1">
        </div>
        <div class="mb-1">
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- Tickets - Cards -->
<div align="right" style="font-size: 80%"><%= page_entries_info @assignee_tasks_paginated, entry_name: 'task' %></div>
<span class="d-flex flex-row-reverse"><%= link_to_next_page @assignee_tasks_paginated, 'Next' %>&nbsp;&nbsp;<%= link_to_previous_page @assignee_tasks_paginated, 'Previous' %></span>
<!-- Tickets - Cards -->
<%= turbo_frame_tag "tasks" do %>
  <div class="row row-cols-1 row-cols-md-3 g-2">
    <% @assignee_tasks_paginated.each do |task| %>
      <%= render partial: "/tasks/task", locals: { task: task } %>
    <% end %>
  </div>
<% end %>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const hoverTexts = document.querySelectorAll(".hover-text");
    const hoverContents = document.querySelectorAll(".hover-content");

    hoverTexts.forEach(function(hoverText, index) {
      hoverText.addEventListener("mouseover", function(event) {
        // Calculate the position of the cursor relative to the viewport
        const x = event.clientX;
        const y = event.clientY;

        // Set the position of the hover content relative to the cursor
        hoverContents[index].style.display = "block";
        hoverContents[index].style.top = `${y + 10}px`;
        hoverContents[index].style.left = `${x + 10}px`;
      });

      hoverText.addEventListener("mouseout", function() {
        hoverContents[index].style.display = "none";
      });
    });
  });
</script>